# Generated by Django 5.0.3 on 2024-08-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('views', models.IntegerField(blank=True, default=0)),
                ('prep_time', models.IntegerField(help_text='Preparation time in mintues')),
                ('cook_time', models.IntegerField(help_text='Cooking time in mintues')),
                ('servings', models.TextField()),
                ('category', models.CharField(max_length=250)),
                ('cuisine', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('author', 'Author'), ('customer', 'Customer')], max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=None)),
                ('bio', models.TextField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Recipe_Sharing_Platform.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Sharing_Platform.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Sharing_Platform.userprofile'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=250)),
                ('date_ordered', models.DateTimeField()),
                ('waiting_time', models.DateTimeField(blank=True, null=True)),
                ('products', models.ManyToManyField(related_name='orders', to='Recipe_Sharing_Platform.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Sharing_Platform.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('recipes', models.ManyToManyField(related_name='collections', to='Recipe_Sharing_Platform.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Sharing_Platform.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe_Sharing_Platform.userprofile')),
            ],
        ),
    ]
