# Generated by Django 5.0.3 on 2024-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Sharing_Platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
