# Generated by Django 5.0.3 on 2024-08-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Sharing_Platform', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentmode',
            name='name',
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='order_is',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_mode', to='Recipe_Sharing_Platform.order'),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'COD'), ('razorpay', 'RazorPay')], default='cod', max_length=50),
            preserve_default=False,
        ),
    ]
