# Generated by Django 5.0.3 on 2024-08-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Sharing_Platform', '0004_remove_paymentmode_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmode',
            old_name='order_is',
            new_name='order',
        ),
    ]
