# Generated by Django 5.0.3 on 2024-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Sharing_Platform', '0005_rename_order_is_paymentmode_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
